import os
import csv
import json
import subprocess
from collections import Counter, defaultdict


# ============================================================
# CONFIGURATION
# ============================================================

REPO_ROOT = os.getcwd()
OUTPUT_DIR = os.path.join(REPO_ROOT, "mining")

# Files/directories that should NOT be included in repository
# inventory because they are generated by this mining script.
EXCLUDED_DIRS = {".git", "mining"}
EXCLUDED_FILES = {"mine_repository.py"}


# ============================================================
# SOURCE CODE LANGUAGE MAPPING
# ============================================================

LANGUAGE_MAP = {
    ".py": "Python",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".java": "Java",
    ".c": "C",
    ".h": "C/C++",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".cs": "C#",
    ".go": "Go",
    ".rs": "Rust",
    ".rb": "Ruby",
    ".php": "PHP",
    ".swift": "Swift",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".scala": "Scala",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".fish": "Shell",
    ".pl": "Perl",
    ".r": "R",
    ".R": "R",
    ".lua": "Lua",
    ".dart": "Dart",
    ".sql": "SQL",
    ".html": "HTML",
    ".css": "CSS",
}


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def run_git(command):
    """Run a Git command and return its output."""
    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )

    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip())

    return result.stdout


def count_loc(file_path):
    """
    Count non-empty lines in a file.
    This is the LOC definition used for this lab.
    """
    try:
        with open(
            file_path,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:
            return sum(
                1
                for line in f
                if line.strip()
            )
    except Exception:
        return 0


def get_extension(file_name):
    """Return file extension or [no extension]."""
    extension = os.path.splitext(file_name)[1].lower()

    if extension:
        return extension

    return "[no extension]"


# ============================================================
# CREATE OUTPUT DIRECTORY
# ============================================================

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================
# REPOSITORY INVENTORY
# ============================================================

total_files = 0
source_code_files = 0
directories = 0
total_loc = 0

languages = Counter()
file_type_distribution = Counter()
source_file_metrics = []


for root, dirnames, filenames in os.walk(REPO_ROOT):

    # Exclude directories such as .git and mining
    dirnames[:] = [
        d for d in dirnames
        if d not in EXCLUDED_DIRS
    ]

    # Count project directories
    for directory in dirnames:
        directories += 1

    for filename in filenames:

        # Ignore the mining script itself
        if filename in EXCLUDED_FILES:
            continue

        full_path = os.path.join(root, filename)

        relative_path = os.path.relpath(
            full_path,
            REPO_ROOT
        )

        # Normalize path separators
        relative_path = relative_path.replace(
            os.sep,
            "/"
        )

        total_files += 1

        extension = get_extension(filename)

        file_type_distribution[extension] += 1

        language = LANGUAGE_MAP.get(extension)

        # Only source-code files are included in source metrics
        if language:

            source_code_files += 1

            loc = count_loc(full_path)

            size_bytes = os.path.getsize(full_path)

            total_loc += loc

            languages[language] += 1

            source_file_metrics.append({
                "file_path": relative_path,
                "language": language,
                "extension": extension,
                "loc": loc,
                "size_bytes": size_bytes
            })


# ============================================================
# LARGEST SOURCE FILES
# ============================================================

largest_source_files = sorted(
    source_file_metrics,
    key=lambda x: x["loc"],
    reverse=True
)[:10]


# ============================================================
# GIT HISTORY
# ============================================================

# ------------------------------------------------------------
# Total commits
# ------------------------------------------------------------

total_commits = int(
    run_git([
        "git",
        "rev-list",
        "--count",
        "HEAD"
    ]).strip()
)


# ------------------------------------------------------------
# Contributors
# ------------------------------------------------------------

author_output = run_git([
    "git",
    "log",
    "--all",
    "--format=%aN <%aE>"
])

author_counter = Counter(
    line.strip()
    for line in author_output.splitlines()
    if line.strip()
)

contributor_identities = len(author_counter)

if author_counter:
    most_active_contributor, most_active_commits = (
        author_counter.most_common(1)[0]
    )
else:
    most_active_contributor = ""
    most_active_commits = 0


# ------------------------------------------------------------
# Commits per month
# ------------------------------------------------------------

commit_month_output = run_git([
    "git",
    "log",
    "--all",
    "--format=%ad",
    "--date=format:%Y-%m"
])

commits_per_month = Counter(
    line.strip()
    for line in commit_month_output.splitlines()
    if line.strip()
)


# ============================================================
# NUMSTAT HISTORY
# ============================================================

"""
Git numstat gives:

additions    deletions    filename

Example:

10    5    src/example.py

For each commit we also print:

COMMIT|YYYY-MM

This allows us to associate each file change with
the month of the commit.
"""

numstat_output = run_git([
    "git",
    "log",
    "--all",
    "--format=COMMIT|%ad",
    "--date=format:%Y-%m",
    "--numstat"
])


monthly_files_changed = Counter()
monthly_additions = Counter()
monthly_deletions = Counter()

file_change_count = Counter()

current_month = None


for line in numstat_output.splitlines():

    line = line.strip()

    # --------------------------------------------------------
    # New commit
    # --------------------------------------------------------

    if line.startswith("COMMIT|"):

        current_month = line.split(
            "|",
            1
        )[1]

        continue

    # Ignore empty lines

    if not line:
        continue

    # --------------------------------------------------------
    # Parse numstat
    # --------------------------------------------------------

    parts = line.split("\t")

    if len(parts) < 3:
        continue

    additions = parts[0]
    deletions = parts[1]
    file_path = parts[2]

    if not current_month:
        continue

    # --------------------------------------------------------
    # Binary files
    #
    # Git represents binary additions/deletions as "-"
    # --------------------------------------------------------

    if additions == "-":
        additions_value = 0
    else:
        try:
            additions_value = int(additions)
        except ValueError:
            additions_value = 0

    if deletions == "-":
        deletions_value = 0
    else:
        try:
            deletions_value = int(deletions)
        except ValueError:
            deletions_value = 0

    # --------------------------------------------------------
    # Monthly statistics
    # --------------------------------------------------------

    monthly_files_changed[current_month] += 1

    monthly_additions[current_month] += additions_value

    monthly_deletions[current_month] += deletions_value

    # --------------------------------------------------------
    # File frequency
    # --------------------------------------------------------

    file_change_count[file_path] += 1


# ============================================================
# MOST FREQUENTLY CHANGED FILES
# ============================================================

most_changed_files = []

for file_path, change_count in file_change_count.most_common(10):

    most_changed_files.append({
        "file": file_path,
        "changes": change_count
    })


# ============================================================
# AVERAGES
# ============================================================

if monthly_files_changed:

    average_files_changed_per_month = (
        sum(monthly_files_changed.values())
        / len(monthly_files_changed)
    )

else:

    average_files_changed_per_month = 0


total_additions = sum(
    monthly_additions.values()
)

total_deletions = sum(
    monthly_deletions.values()
)


if total_commits > 0:

    average_additions_per_commit = (
        total_additions
        / total_commits
    )

    average_deletions_per_commit = (
        total_deletions
        / total_commits
    )

else:

    average_additions_per_commit = 0
    average_deletions_per_commit = 0


# ============================================================
# FILE METRICS CSV
# ============================================================

file_metrics_csv = os.path.join(
    OUTPUT_DIR,
    "file_metrics.csv"
)

with open(
    file_metrics_csv,
    "w",
    newline="",
    encoding="utf-8"
) as csv_file:

    writer = csv.writer(csv_file)

    writer.writerow([
        "file_path",
        "language",
        "extension",
        "loc",
        "size_bytes"
    ])

    for file_data in sorted(
        source_file_metrics,
        key=lambda x: x["file_path"]
    ):

        writer.writerow([
            file_data["file_path"],
            file_data["language"],
            file_data["extension"],
            file_data["loc"],
            file_data["size_bytes"]
        ])


# ============================================================
# GIT HISTORY CSV
# ============================================================

git_history_csv = os.path.join(
    OUTPUT_DIR,
    "git_history.csv"
)

with open(
    git_history_csv,
    "w",
    newline="",
    encoding="utf-8"
) as csv_file:

    writer = csv.writer(csv_file)

    writer.writerow([
        "month",
        "commits",
        "files_changed",
        "additions",
        "deletions"
    ])

    all_months = sorted(
        commits_per_month.keys()
    )

    for month in all_months:

        writer.writerow([
            month,
            commits_per_month[month],
            monthly_files_changed[month],
            monthly_additions[month],
            monthly_deletions[month]
        ])


# ============================================================
# JSON STATISTICS
# ============================================================

repository_stats = {

    "repository": "psf/requests",

    "inventory": {

        "total_files": total_files,

        "source_code_files": source_code_files,

        "directories": directories,

        "total_loc": total_loc,

        "languages": dict(languages),

        "file_type_distribution": dict(
            file_type_distribution
        ),

        "largest_source_files": largest_source_files
    },

    "git_history": {

        "total_commits": total_commits,

        "contributors": contributor_identities,

        "most_active_contributor": {

            "identity": most_active_contributor,

            "commits": most_active_commits
        },

        "most_changed_files": most_changed_files,

        "commits_per_month": dict(
            sorted(commits_per_month.items())
        ),

        "average_files_changed_per_month": round(
            average_files_changed_per_month,
            2
        ),

        "average_additions_per_commit": round(
            average_additions_per_commit,
            2
        ),

        "average_deletions_per_commit": round(
            average_deletions_per_commit,
            2
        )
    }
}


json_file = os.path.join(
    OUTPUT_DIR,
    "repository_stats.json"
)

with open(
    json_file,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        repository_stats,
        f,
        indent=4
    )


# ============================================================
# DISPLAY RESULTS
# ============================================================

print()
print("==========================================")
print("       REPOSITORY MINING COMPLETE")
print("==========================================")

print(f"Repository: psf/requests")

print(f"Total files: {total_files}")

print(f"Source files: {source_code_files}")

print(f"Directories: {directories}")

print(f"Total LOC: {total_loc}")

print()
print("Git History")
print("------------------------------------------")

print(f"Total commits: {total_commits}")

print(
    f"Contributor identities: "
    f"{contributor_identities}"
)

print(
    f"Most active contributor: "
    f"{most_active_contributor} | "
    f"{most_active_commits} commits"
)

print(
    f"Average files changed/month: "
    f"{average_files_changed_per_month:.2f}"
)

print(
    f"Average additions/commit: "
    f"{average_additions_per_commit:.2f}"
)

print(
    f"Average deletions/commit: "
    f"{average_deletions_per_commit:.2f}"
)

print()
print("Generated files:")
print("------------------------------------------")

print("mining/file_metrics.csv")
print("mining/git_history.csv")
print("mining/repository_stats.json")

print()
print("==========================================")